OmniJaws:  Override startup provider due to resource loading issue
Fixes:
  /home/......./APPS/OmniJaws_intermediates/manifest/AndroidManifest.xml.fixed:43:13-75
  Error: Attribute provider#androidx.startup.InitializationProvider@authorities v
alue=(com.android.settingslib.androidx-startup) from AndroidManifest.xml:43:13-7
5 is also present at AndroidManifest.xml:34:13-78 value=(androidx.legacy.p
reference.androidx-startup).
      Suggestion: add 'tools:replace="android:authorities"' to <provider> elem
ent at AndroidManifest.xml.fixed:41:9-52:20 to override.

Signed-off-by: George Zacharia <george.zcharia@gmail.com>
Signed-off-by: Semavi Ulusoy <doc.divxm@gmail.com>
Change-Id: I2b6e0e2c7a36872b04acd7db7c66ac6a9b7b1a79